### ISSUE TITLE
該字詞「鱂魚」無法反查注音

### ISSUE THREAD

**Issue by jjyao88** [huanlin/nchinese#14]
作者您好！

當我使用套件的時候發現，「鱂」這個字似乎沒有被收錄字典裡面，導致反查時會回傳空陣列。

**Comment by huanlin** [comment]
@jjyao88 抱歉，直到今天才發現您的留言，而且 issue 已經關閉。請問是否已經解決？

**Comment by jjyao88** [comment]
哈囉！我後來嘗試自己新增自訂辭典解決了，原本的注音語庫反查會有問題
